-- 성분으로 구분한 아이스크림 총 주문량 : https://school.programmers.co.kr/learn/courses/30/lessons/133026
-- 스스로 해결 여부 : O

SELECT I.INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS F
JOIN ICECREAM_INFO AS I ON F.FLAVOR = I.FLAVOR
GROUP BY I.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER